CREATE TABLE `t_sales_shop` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL,
  `URL` varchar(128) DEFAULT NULL,
  `CREATED_BY` varchar(128) DEFAULT NULL,
  `UPDATED_BY` varchar(128) DEFAULT NULL,
  `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_AT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `INITIAL_DT` datetime DEFAULT NULL,
  `LAST_SCAN_DT` datetime DEFAULT NULL,
  `CATEGORY` varchar(64) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `NAME` (`NAME`),
  KEY `URL` (`URL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

