CREATE TABLE `t_sales_product` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TAOBAO_ID` bigint(20) NOT NULL,
  `TITLE` varchar(255) DEFAULT NULL,
  `THUMBNAIL` varchar(255) DEFAULT NULL,
  `UNIT_PRICE` decimal(10,0) unsigned zerofill DEFAULT NULL,
  `SALES_AMOUNT` bigint(20) DEFAULT NULL,
  `RATING` double DEFAULT NULL,
  `LINK` varchar(255) DEFAULT NULL,
  `SHOP_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_SHOP_ID_CONSTRAINT` (`SHOP_ID`),
  CONSTRAINT `FK_SHOP_ID_CONSTRAINT` FOREIGN KEY (`SHOP_ID`) REFERENCES `t_sales_shop` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;

