
DROP TABLE IF EXISTS `taobaomonitor_schema`.`t_sales_deal`;
DROP TABLE IF EXISTS `taobaomonitor_schema`.`t_sales_product`;
DROP TABLE IF EXISTS `taobaomonitor_schema`.`t_sales_shop`;
DROP TABLE IF EXISTS `taobaomonitor_schema`.`t_sales_report`;


CREATE TABLE `t_sales_shop` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL,
  `URL` varchar(128) DEFAULT NULL,
  `CREATED_BY` varchar(128) DEFAULT NULL,
  `UPDATED_BY` varchar(128) DEFAULT NULL,
  `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_AT` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `INITIAL_DT` datetime DEFAULT NULL,
  `LAST_SCAN_DT` datetime DEFAULT NULL,
  `CATEGORY` varchar(64) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `NAME` (`NAME`),
  KEY `URL` (`URL`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `t_sales_product` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TAOBAO_ID` bigint(20) NOT NULL,
  `TITLE` varchar(255) DEFAULT NULL,
  `THUMBNAIL` varchar(255) DEFAULT NULL,
  `UNIT_PRICE` decimal(10,0) unsigned zerofill DEFAULT NULL,
  `SALES_AMOUNT` bigint(20) DEFAULT NULL,
  `RATING` double DEFAULT NULL,
  `LINK` varchar(255) DEFAULT NULL,
  `SHOP_ID` bigint(20) NOT NULL,
  `CREATED_BY` varchar(128) DEFAULT NULL,
  `UPDATED_BY` varchar(128) DEFAULT NULL,
  `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_AT` timestamp,
  PRIMARY KEY (`ID`),
  KEY `FK_SHOP_ID_CONSTRAINT` (`SHOP_ID`),
  KEY `TAOBAO_ID` (`TAOBAO_ID`),
  KEY `RATING` (`RATING`),
  CONSTRAINT `FK_SHOP_ID_CONSTRAINT` FOREIGN KEY (`SHOP_ID`) REFERENCES `t_sales_shop` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `t_sales_deal` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UNIT_PRICE` decimal(10,0) unsigned zerofill DEFAULT NULL,
  `SALES_AMOUNT` int(10) unsigned zerofill DEFAULT NULL,
  `TOTAL_PRICE` decimal(10,0) unsigned zerofill DEFAULT NULL,
  `DEAL_DATE` datetime NOT NULL,
  `PRODUCT_ID` bigint(20) NOT NULL,
  `CREATED_BY` varchar(128) DEFAULT NULL,
  `UPDATED_BY` varchar(128) DEFAULT NULL,
  `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_AT` timestamp,
  PRIMARY KEY (`ID`),
  KEY `FK_PRODUCT_ID_CONSTRAINT` (`PRODUCT_ID`),
  KEY `DEAL_DATE` (`DEAL_DATE`),
  CONSTRAINT `FK_PRODUCT_ID_CONSTRAINT` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `t_sales_product` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `t_sales_report` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SHOP_ID` bigint(20) NOT NULL,
  `PRODUCT_ID` bigint(20) NOT NULL,
  `REPORT_TYPE` varchar(20) DEFAULT NULL,
  `DATE_TO` date DEFAULT NULL,
  `RANK` varchar(11) DEFAULT NULL,
  `TOTAL_SALE_AMOUNT` bigint(20) DEFAULT NULL,
  `TOTAL_REVENUE` decimal(10,0) DEFAULT NULL,
  `CREATED_BY` varchar(128) DEFAULT NULL,
  `UPDATED_BY` varchar(128) DEFAULT NULL,
  `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_AT` timestamp,
  PRIMARY KEY (`ID`),
  KEY `FK_SALES_REPORT_SHOP_ID_CONSTRAINT` (`SHOP_ID`),
  KEY `FK_SALES_REPORT_PRODUCT_ID_CONSTRAINT` (`PRODUCT_ID`),
  CONSTRAINT `FK_SALES_REPORT_SHOP_ID_CONSTRAINT` FOREIGN KEY (`SHOP_ID`) REFERENCES `t_sales_shop` (`ID`),
  CONSTRAINT `FK_SALES_REPORT_PRODUCT_ID_CONSTRAINT` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `t_sales_product` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

